# Generated by Django 3.1.7 on 2021-03-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='FILE',
            field=models.FileField(blank=True, null=True, upload_to='Assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('FILE', models.FileField(blank=True, null=True, upload_to='Submissions/')),
                ('assignment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.assignment')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
    ]
