# Generated by Django 2.2.5 on 2021-03-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='professor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Professor',
            new_name='Professor_name',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Courses',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user_name',
        ),
    ]
