# Generated by Django 2.2.5 on 2021-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210309_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
